name: ui_showcases
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  go_router: ^15.0.0
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.6.1
  http: ^1.3.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^3.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  lint: ^2.8.0
  riverpod_generator: ^2.6.5


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/ 
    - assets/images/
    - assets/icons/
    - assets/icons/tiktok/
